### PR TITLE
fixes on the emoji icon ui

### PR DESCRIPTION
**Pull request by ayeolakenny**
Had issues with syncing the forks, this is a new pull request, happy to fix more bugs :)

### CODE REVIEW

**Comment by ayeolakenny** [comment]
I did not enocounter the autocomplete or am i getting something wrong?

**Comment by manuelalferez** [comment]
I noticed that you closed the previous pull request #13, it is a good practice to keep all the changes related to an improvement in the same pull request, in order to have control of the changes that pull request has undergone.

Very likely you had problems updating your previous pull request. Let me know if you have a problem with that and we see it together. 

If that's not the case, please update the pull request #13 with the changed that you added to this one #20.

**Comment by manuelalferez** [comment]
I am using Google Chrome, but I think it should be a problem with the styles of tailwind. Let me know if you can solve it @ayeolakenny

**Comment by ayeolakenny** [comment]
Hello @manuelalferez kindly check if the bug still persists, :)

**Pull request closed without merging**
